name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build ccache python3 python3-tk

    - name: Install Python packages
      run: python -m pip install --user -r tools/wm/requirements.txt

    - name: Download and extract csky-elfabiv2-tools
      run: |
        curl -L https://zone.winnermicro.net:60443/wmios/tools/linux/csky-elfabiv2-tools-x86_64-minilibc-20210423.tar.gz --output csky-elfabiv2-tools.tar.gz
        tar -xzf csky-elfabiv2-tools.tar.gz -C /home/wm/tools

    - name: Set environment variables for Toolchain and WM IoT SDK
      run: |
        echo "PATH=/home/wm/tools/csky-elfabiv2-tools/bin:$PATH" >> $GITHUB_ENV
        echo "WM_IOT_SDK_PATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "PATH=$WM_IOT_SDK_PATH/tools/wm:$PATH" >> $GITHUB_ENV
        echo "$GITHUB_ENV"
